### ISSUE TITLE
How to introduce the LAScatalog processing engine

### ISSUE THREAD

**Issue by Jean-Romain** [r-lidar/lidRbook#1]
Two ways. The  first one is the one I used in my workshops. It consists in presenting everything with point cloud loaded in memory without mentioning anything about broad coverage and later describe the LAScatalog engine. The second option is to always present both in the same time. For the book we have to choose one of those ways.

In the first case the content looks like this

- DTM on a point cloud
- Normalization on a point cloud
- DSM on a point cloud
- ABA on a point cloud
- TBA on a poin cloud
- PBA on a point cloud
- LAScatalog with DTM, normalisation, DSM, ABA, TBA examples

In the second case the content looks like this

- DTM on a point cloud then catalog
- Normalization on a point cloud then catalog
- DSM on a point cloud then catalog
- ABA on a point cloud then catalog
- TBA on a point cloud then catalog
- PBA on a point cloud

My preference goes to the first option because it is the one I'm used with and it allows to put all the LAScatalog information in one place without repetition. We must consider that the chapters won't be read in order . Maybe a reader who is reading the ABA section did not read the section DTM. So in the second option we must repeat ourself a lot (much more at least).

**Comment by tgoodbody** [comment]
The way you implemented it is great JR I think its the right way.
