### ISSUE TITLE
Error in enquo(colour_by) : could not find function "enquo"

### ISSUE THREAD

**Issue by jocelynpender** [r-lidar/lidRbook#11]
I'm working through Chapter 2 of the [lidr book.](https://r-lidar.github.io/lidRbook/io.html)

When I run this code:
```
plot_crossection <- function(las,
                             p1 = c(min(las@data$X), mean(las@data$Y)),
                             p2 = c(max(las@data$X), mean(las@data$Y)),
                             width = 4, colour_by = NULL)
{
  colour_by <- enquo(colour_by)
  data_clip <- clip_transect(las, p1, p2, width)
  p <- ggplot(data_clip@data, aes(X,Z)) + geom_point(size = 0.5) + coord_equal() + theme_minimal()

  if (!is.null(colour_by))
    p <- p + aes(color = !!colour_by) + labs(color = "")

  return(p)
}
```
I get this error: `Error in enquo(colour_by) : could not find function "enquo"`. It looks like [enquo is a function from the rlang package](https://rlang.r-lib.org/reference/enquo.html). If this package is necessary for running the code block, perhaps this could be stated? Alternatively, should I already have installed `rlang`?

R version 4.1.1 (2021-08-10)
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
lidR version 4.0.2

**Comment by Jean-Romain** [comment]
I  change the code explictely call `enquo` by namespace. Thanks
