### ISSUE TITLE
Bookwide search 

### ISSUE THREAD

**Issue by tgoodbody** [r-lidar/lidRbook#14]
Hi JR,

The search (magnifying glass) option in the book is currently limited to content on the current viewable page. It looks like there is a method to allow searches across all content.

I'm using [bookdown](https://bookdown.org/yihui/bookdown/) as a comparison. The search function provides matches from all content regardless of page. Some digging seems to indicate that there is an option to specify the search type in the book `_output.yml`.

https://github.com/rstudio/bookdown/blob/e3cae95282f497c55864057e9e8255e2aed75120/inst/examples/_output.yml#L18C11-L18C11

https://stackoverflow.com/questions/68784830/bookdown-how-to-switch-to-fuse-search-engine-and-set-options

Based on those sources it looks like specifying the `search` will allow this useful functionality.

**Comment by tgoodbody** [comment]
@Jean-Romain I have added the search functionality but am running into: 

`Error: NULL value passed as symbol address` error in the [lascatalog processing engine section](https://r-lidar.github.io/lidRbook/engine2.html#engine-user-function-extended). Not sure if its a local machine issue, but I cant render these outputs. I don't have the know how to address what I assume to be a background C++ issue.

I have commented the problematic lines out and used `bookdown::serve_book()` to test the output, which allows cross-book search functionality. 

I will do a PR with these commented changes, but it is likely that you will need to try to re-render the book on your end to fix the visualization of those features.

**Comment by Jean-Romain** [comment]
This is an error with `terra` and parallel processing. I'm tired of finding workaround for this problem here and there because `terra` is badly designed with non serializable objects. I should not have switched to `terra`. Now I'm struggling with finding workaround everywhere. I'll have a look mid August
