### ISSUE TITLE
Render whole book and provide to selection of people as an Alpha version

### ISSUE THREAD

**Issue by tgoodbody** [r-lidar/lidRbook#2]
Ive gone through all the pages of the book and made edits. I think it looks great and is exactly what we originally intended it to be. Nice job @Jean-Romain @ptompalski  you guys did some really great coding work and I think this will be hugely valuable for alot of people.

I think maybe the next logical step is to render the book and make it available online to a selection of people for them to trouble shoot and look for errors that they can pass along to me. It makes sense to me that we first open it to people in IRSS / Achim lab and get some people to review it for style/errors/typos. After that I think its probably time to make it public.

Thoughts?

**Comment by tgoodbody** [comment]
One thing we might want to do is clean up the naming conventions of the individual file pages. Right now the numbers are not sequential anymore. Ill leave this to you JR - I want to make sure file names etc are done the way you want them.

**Comment by Jean-Romain** [comment]
Right, there is some clean up to do. Not only in the file names but also in the code snippets. Also I'd like to read the whole book myself first. So far I read it many times but in random orders. But yes we are close. Please push everything you have and let me work on it.

Do we keep it private and we invite a 4th contributor or do we rely on IRSS team to review a first public beta-release. We need English native speakers for sure. You @tgoodbody  have made a very good work but I'm still able to spot many typos here and there. It's not your fault, you started with a very raw material.

We can't really count on Achim's lab. They are not lidR user and/or not native speakers. One of us is becoming a lidR user however. He could give us some feed back on the content.

**Comment by Jean-Romain** [comment]
We need to add a disclaimer in intro to mention this **is not** the documentation of the package. Just some tutorials. You know what i mean :wink:

**Comment by Jean-Romain** [comment]
Also we have a very nasty problem. With the release of `rgdal 1.5-8` there are many dummy warnings everywhere in the book.

**Comment by tgoodbody** [comment]
yes i understand about the typos - something i want is to have the whole book rendered so i can read it thoruhg entirely in the rendered format so i can catch those typo's easier. Getting it to the IRSS for corrections would be pretty easy i think. If we have a URL that we dont make public to all yet we can get people to access it and read through. I also imagine alot of IRSS people will find it useful as is - and would be happy to add feedback where needed.

Do you want me to add a disclaimer in the into section now?

**Comment by tgoodbody** [comment]
i went ahead and added a disclaimer - edit as you like
