### ISSUE TITLE
Issue for the full rendering

### ISSUE THREAD

**Issue by Jean-Romain** [r-lidar/lidRbook#3]
A bunch of issue I'm finding while I'm reading the whole book

# Whole book

- [x] cross references
```
1: In make_shadow(heightmap, shadowdepth, shadowwidth, background,  :
  `magick` package required for smooth shadow--using basic shadow instead.
2: Invalid file: the data contains a 'RGB' field but point data format is not set to 2, 3, 5, 7, 8 or 10 
3: Invalid data: RGB colors are recorded on 8 bits instead of 16 bits. 
4: Invalid file: the data contains a 'RGB' field but point data format is not set to 2, 3, 5, 7, 8 or 10 
5: The label(s) engine1 not found 
6: The label(s) lascatalog not found 
7: The label(s) VBA not found 
8: The label(s) PBA not found 
```
- [x] point-cloud vs. point cloud consistency
- [x] rename files
- [ ] rename data folders
- [x] we often make cross reference using the word section instead of chapter `section \@ref(engine)`
- [x] use `<-` instead of `=` consistantly

# 1 index

- [ ] on the bottom this is rendered

```
## <STYLE type='text/css' scoped>
## PRE.fansi SPAN {padding-top: .25em; padding-bottom: .25em};
## </STYLE>
```

# 2 io

- [x] 2-io_display. Figure L121 is not properly rendered and it is not *the* rgl bug. Colors are incorrect the points are blues instead of rainbow. 
- [x] 2-io_display. Figure L138 is not properly rendered and it is not *the* rgl bug. Colors are incorrect the points are red instead of yellowish gradient. 
- [x] `rgdal` nasty warning

# 3 gnd

- [x] `rgdal` nasty warning

# 4 dtm

- [x] `rgdal` nasty warning
- [ ]  when knitting

 ```
Output created: _book/dtm.html
Warning messages:
1: In xfun::prose_index(x) : Code fences are not balanced
2: In make_shadow(heightmap, shadowdepth, shadowwidth, background,  :
  `magick` package required for smooth shadow--using basic shadow instead.
```

# 5 norm

- [x] `rgdal` nasty warning
- [ ] when knitting

```
Output created: _book/norm.html
Warning messages:
1: In xfun::prose_index(x) : Code fences are not balanced
2: In showSRID(SRS_string, format = "PROJ", multiline = "NO") :
  PROJ6/GDAL3 PROJ string degradation in workflow
 repeated warnings suppressed
 Discarded datum NAD83_Canadian_Spatial_Reference_System in CRS definition
```

# 6 CHM

- [x] `rgdal` nasty warning
- [ ] The text is a little bit coarse. I want to add more explanation
- [x] progress bar are rendered when `bookdown::render_book()` but not with <kbd>knit</kbd> button

# 7 ITD

- [x] inconsitant rgl orientation compared to the rest of the book
- [ ] when knitting

```
Output created: _book/itd.html
Warning message:
In xfun::prose_index(x) : Code fences are not balanced
```
- [x] `rgdal` nasty warning

# 8 Metrics

Nothing

# 9 CBA

- [ ] when knitting

```
Output created: _book/cba.html
Warning message:
In xfun::prose_index(x) : Code fences are not balanced
```

- [x] incorrect cross reference

# 10 ABA

- [ ] when knitting

```
Output created: _book/aba.html
Warning message:
In xfun::prose_index(x) : Code fences are not balanced
```

- [x] incorrect cross reference

# 11 TBA

- [ ] when knitting

```
Output created: _book/tba.html
Warning message:
In xfun::prose_index(x) : Code fences are not balanced
```

# 12 VBA

- [ ] when knitting

```
Output created: _book/vba.html
Warning message:
In xfun::prose_index(x) : Code fences are not balanced
```

# 13 PBA

- [ ] when knitting

```
Output created: _book/vba.html
Warning message:
In xfun::prose_index(x) : Code fences are not balanced
```

# 14 engine

- [ ] cache is invalidated when rendering the book in a new session
- [x] `rgdal` nasty warning
- [ ] when knitting

```
Output created: _book/engine.html
Warning message:
In xfun::prose_index(x) : Code fences are not balanced
```
- the title levels must be reviewed

# 15 engine

- [ ] when knitting

```
Output created: _book/engine2.html
Warning message:
In xfun::prose_index(x) : Code fences are not balanced
```

# 16 Modelling

- [ ] The rendering is not dynamically produced

# 17 outbox

- [x] RGB grid_metrics output black instead of NA

# 18 plugins

- [x] [WARNING] Duplicate identifier 'modelling' at line 244 column 1
- [ ] knitting

```
Output created: _book/plugins.html
Warning message:
In xfun::prose_index(x) : Code fences are not balanced
```

**Comment by tgoodbody** [comment]
i did my best to change the point-cloud to point cloud

**Comment by tgoodbody** [comment]
Nicholas also OK'd giving the rendered book to some IRSS people so when these issues are resolved we can move ahead with that.

Is there anything here you want me to focus on or do you intend to tick off these boxes?

**Comment by Jean-Romain** [comment]
First I'll create all the boxes then I'll fix them all.

**Comment by Jean-Romain** [comment]
I think we need an illustrated appendix for edge artifact. This will allow use to put cross reference to this appendix in several chapters

**Comment by tgoodbody** [comment]
Hi JR - ive gotten feedback from a few people in IRSS about the open version of the book.

Ive gotten them to fill out comments they had in a google doc. https://docs.google.com/document/d/1rWmm9plhCLVg7lOPuzFbm49gRHe5hNrIbvycCPs6950/edit

I know youre not keen on word documents :) so ive made #4 . See my comment at the end regarding starting/finishing edits.

**Comment by tgoodbody** [comment]
I've gone through all the section headers and links now @Jean-Romain. I think they are appropriate now.. A few were quite long so I shortened them.

Also thoroughly checked the code snippets for consistency using "<-" over "=". Not alot of changes to be made but there we a few.
