### ISSUE TITLE
IRSS Corrections

### ISSUE THREAD

**Issue by tgoodbody** [r-lidar/lidRbook#4]
## Section 2:

- [x] 2.1.2 For example the R function to filter points of interest (POI) is` filter_poi()` may return the exact same output than the filter option in readLAS(): should be For example, the R function to filter points of interest (POI), `filter_poi()`, may return the exact same output as the filter option in `readLAS()`:

- [x] 2.3.3 we extract the coordinates and sizes of the trees an plot lines with `rgl::segment3d`. Should be we extract the coordinates and sizes of the trees and plot lines with rgl::segment3d.

## Section 3:

section | Original | corrected
-- | -- | --
3.1 | More experienced user may experiment with these parameters to achieve best classification accuracy, | More experienced users may experiment with these parameters to achieve the best classification accuracy,
3.2 | Cloth simulation filtering (CSF) is based on Zhang et al 2016 and consists in simulating a piece of cloth draped on top of a reversed point cloud | Cloth simulation filtering (CSF) is based on Zhang et al 2016 and consists of simulating a piece of cloth draped on top of a reversed point cloud.
3.2 | While the default parameters of csf() are designed to be universal and provide accurate classification results according to the original paper, it is apparent that the algorithm did not work properly in our example with a significant portion of points located in the ground were not classified. | While the default parameters of `csf()` are designed to be universal and provide accurate classification results according to the original paper, it is apparent that the algorithm did not work properly in our example because a significant portion of points located in the ground were not classified.
3.3 | No matter which algorithm is used in lidR or other software, ground classification will be weaker at the edges of point clouds. To find ground points, an algorithm need to analyze the local neighborhood or local context that is missing at edge areas. | No matter which algorithm is used in `lidR` or other software, ground classification will be weaker at the edges of point clouds, as the algorithm must analyze the local neighborhood or local context -- which is missing on edges.

## Section 4:

- [x] The construction of a DTM is simply a spatial interpolation of the ground points at unsampled locations.

I think this should be reworded a bit to say that it starts with known or sampled ground points and uses various spatial interpolation techniques to infer ground points at unsampled locations.

- [x] (between the ground points) - Between the known ground points

- [x] The Delaunay triangulation is unique and the linear interpolation is parameter-free - The Delaunay triangulation is unique **as** the linear interpolation is parameter-free

- [x] The drawbacks of the method are that it creates a non-smooth DTM and that it cannot extrapolate the terrain outside the convex hull delimited by the ground points since there is no triangle facets outside the convex hull.  - The drawbacks of the method are that it creates a non-smooth DTM and that it cannot extrapolate the terrain outside the convex hull delimited by the ground points since there **are no** triangle facets outside the convex hull.

- [x] This occurs because we didnt process with a buffer. This occurs because we didn't process with a buffer.

- [x] Invert distance weighting (IDW) is one of the simplest and most readily available methods that can be applied to create DTM. - Either make DTM plural or say a DTM.

- [x] but approximately twice slower than TIN - Should this be twice as slow?

- [x] Many more were have been presented and described in the literature. - Remove “were”

- [x] In section 18 will learn how to create an plugin algorithm compatible with grid_terrain() based on a multilevel B-spline approximation (MBA) using the MBA package. - In section 18 **we** will learn how to create **a** plugin algorithm compatible with grid_terrain() based on a multilevel B-spline approximation (MBA) using the MBA package.

## Section 5:

- [x] In this case, however it doesn’t seem to have helped, perhaps even making it worse. - I’d drop “however” or move it to the beginning of the sentence 

- [x] It is also important to recall here that the question of buffer and edge artifact also applies here. - Having “here” twice sounds clunky 

## Section 6:

- [ ] `chm <- grid_canopy(las, res = 0.5, p2r(0.2, na.fill = tin()))` - Geometry package is required to be installed separately in order for this to work, possible it could be installed w/ lidR? As a dependency if the tin operation is commonly used?

### Section 6.2:

- [x] If set to e.g. 8 it means that every ttriangle with an edge longer than 8 will be discarded from the triangulation.

### Section 7.1.1:

- [x]  window size = 5m but radius is 2.4m each side of the point. Should say 2.5m?

- [x]  “This can be seen in the figure below where only the dominant trees are found with a large windows size and too many trees are found with a small windows size.” - figure shows lots of trees on left, few trees on right. Perhaps switch order here to be consistent?

### Section 7.1.2:

- [x] 7.1.2: “A large window**s** is suitable for” - window

- [x] 7.1.2: “a point at 30 m (a big tree) will be tested with a large neighbourhood, while a point at 10 m (a smaller tree) will be tested with a smaller window.” Keep consistent, say neighbourhood twice or window twice.

### Section 7.2:

- [x] Raster-based that using a CHM.Using should be used

## Section 8:

- [x] Paragraph 2: “Irregardless” - regardless is more commonly used

### Section 8.1:

- [x] “Al the function work” - should be ‘All’

### Section 8.2:

- [x] “For example, to calculate the mean and standard deviation of elevation & the mean intensity, the following function can be used” but code block shows the mean elevation, sd of intensity and mean intensity. 

## Section 9:

- [x] In 8, ‘.stdmetrics’ is introduced. Somewhat unclear when ‘.stdmetrics_rn’ is used in Section 9 (it looks like it just produces metrics for return number), but might be worthwhile to mention that there are subsets of ‘.stdmetrics’ (e.g. .stdmetrics_z).

## Section 10.1:

- [x] Paragraph 1: ‘cahpter’ instead of ‘chapter’

## Section 13:

- [x] 13.1: “In the following, the mean intensity is …” Could change to “In the following (example, code block, etc.)

- [x] 13.2.1: “First we need to defined a function that computes …” - Change to “define”

## Section 14:

- [ ] Suggestion “On disk DTM (14.10.2)” include an example of reading light rasters, I think that could be useful.

- [x] “14.11 Storage Summary” some text missing here. Say: “in this section” or “section 10”.

- [x] “14.13 Area Based Approach”: - Be consistent with the use of hyphen. 

- [x] Conjonction → Conjunction. 

- [x] Two more options do however exist that are not controllable in each function → should it be every function?

- [x] Does limiting selection of column LAS speed up processing of function X, e.g. grid_metrics.

- [x] I would expect a summary as well at the end of section 14. Are the summaries still in development? They are quite useful :)

## Section 15:

- [x] “The power of the engine goes beyond those limited used case and allows developers to design their own applications.” → awkward sentence

- [x] “15.1 catalog_apply()”: one of the hyperlinks under “here and here” is broken.

- [x] “The purpose of these examples is to provide alternative, hands on documentation with more applied examples and real use cases.” → hands-on , should be hyphenated

- [x] Suggestion for “15.2 Create user-defined function”: State that the example is just following standard R syntax and include link to R programming manual on how to write your own functions: https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Writing-your-own-functions.

## Section 16:

- [x] Button on Table of contents(Left side of screen) does not redirect properly 

## Section 17:

- [x] Each channels returns vary in intensities as seen in the figure below because of the wavelength reflectance properties of the targets.

- [x] Channels -> channel’s

**Comment by tgoodbody** [comment]
@Jean-Romain let me know when you are finished with #3 and ill finish these changes afterwards and go through book again

**Comment by Jean-Romain** [comment]
Just go for it. I don't know how to fix most of the remaining boxes yet in #3.

**Comment by tgoodbody** [comment]
OK will do

**Comment by Jean-Romain** [comment]
About comment for section 6 this is likely to be a bug. It should work without geometry. will see

**Comment by Jean-Romain** [comment]
> `chm <- grid_canopy(las, res = 0.5, p2r(0.2, na.fill = tin()))` - Geometry package is required to be installed separately in order for this to work, possible it could be installed w/ lidR? As a dependency if the tin operation is commonly used?

Who made this comment and how they figured out that `geometry` was required? It is not, it works without `geometry` but I indeed found an potential bug where code may fall back to the old method. But I can't reproduce easily.

**Comment by Jean-Romain** [comment]
> Suggestion “On disk DTM (14.10.2)” include an example of reading light rasters, I think that could be useful.

Well, there is an example and the dtm is loaded automatically there is nothing else to say. The display is exactly the same as above so I did not included an image. What kind of information was actually expected?
