### ISSUE TITLE
Probably missing/broken link in 14.12

### ISSUE THREAD

**Issue by Lenostatos** [r-lidar/lidRbook#7]
Dear Authors of the lidR book,

I think I've found a missing link in the book in chapter 14 (catalog engine 1/2), section 12 (individual tree segmentation). At the end of the second sentence it says "see section (itd)" and I'm guessing that the "(itd)" part is supposed to link to chapter 7.2 (individual tree segementation).

Link to the markdown code for that sentence:
https://github.com/Jean-Romain/lidRbook/blob/f9e2db13b273d27b4ee4601dcb4197f087abd26c/14-engine.Rmd#L414

Cheers, Leon

**Comment by Jean-Romain** [comment]
Thank you for reporting
